name: build checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: ros:noetic
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install --from-paths src -qr --ignore-src --default-yes
      - name: Build packages
        run: /opt/ros/noetic/env.sh catkin_make
